### ISSUE TITLE
why I always have a error?

### ISSUE THREAD

**Issue by hildegardvonsun** [yukai-yang/PSTR#9] opened 2022-05-27 10:33 UTC
Error in if (class(invS1) == "try-error") { :    the condition has length > 1
R:4.2.0.

**Comment by GaoliangWang** [comment] 2022-09-21 13:33
> pstr = LinTest(use=pstr) 
Error in if (class(invS1) == "try-error") { : 
  the condition has length > 1

**Comment by MarvinMeng1** [comment] 2022-10-16 14:50
same question
how to solve it

**Comment by hildegardvonsun** [comment] 2022-10-18 11:10
Using special R（maybe 4.3.0，see the code author said what heused）。With many packages，then perhaps you can use it！！！










At 2022-10-16 22:50:17, "MarvinMeng1" ***@***.***> wrote:

same question
how to solve it

**Comment by yukai-yang** [comment] 2022-10-19 12:18
Sorry for the late reply! The problem is due to the fact that the current R version (v.4) may return multiple values (as a vector), which is different from the previous versions of R (<=3). My suggestion is that you can use the previous versions of R and try it.

This is also the reason why you cannot see the package on CRAN now.

The package will be updated soon and the problem will be fixed in the next version.

Thanks for reporting the problem!

**Comment by yukai-yang** [comment] 2023-01-11 18:49
Should have been fixed!

**Closed as completed by yukai-yang** 2023-01-11 18:49 UTC
