### ISSUE TITLE
Problems running the package in R version 4.0.3.

### ISSUE THREAD

**Issue by sandramacheri2498** [yukai-yang/PSTR#8] opened 2021-12-09 04:23 UTC
Hello!
I have problems running the package in R version 4.0.3.
Will they have an updated version of the code?

Thanks!

**Comment by MengfanDu** [comment] 2022-04-27 11:49
Hi, I get an error when running your code，details as follows：
> pstr = LinTest(use=pstr) 
Error in if (class(invS1) == "try-error") { : 
  the condition has length > 1
How should this problem be solved？
thank you!

**Comment by yukai-yang** [comment] 2022-10-19 12:20
Sorry for the late reply! The problem is due to the fact that the current R version (v.4) may return multiple values (as a vector), which is different from the previous versions of R (<=3). My suggestion is that you can use the previous versions of R and try it.

This is also the reason why you cannot see the package on CRAN now.

The package will be updated soon and the problem will be fixed in the next version.

Thanks for reporting the problem!

**Comment by yukai-yang** [comment] 2023-01-11 18:49
Should have been fixed!

**Closed as completed by yukai-yang** 2023-01-11 18:49 UTC
